version: "2.4"

services:
  mysqldb:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    restart: unless-stopped
    ports:
      - "3366:${DB_HOST_PORT}"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    volumes:
      - mysql_data:/var/lib/mysql

  graphql-api:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["yarn", "start"]
    depends_on:
      mysqldb:
        condition: service_healthy
    environment:
      - "DB_USER=${DB_USER}"
      - "DB_NAME=${DB_NAME}"
      - "DB_PASSWORD=${DB_PASSWORD}"
      - DB_HOST_NAME=mysqldb
      - "DB_HOST_PORT=${DB_HOST_PORT}"
    ports:
      - 8080:8080
    restart: unless-stopped

volumes:
  mysql_data:
